/// Maps country names and F1 driver nationalities to flag emoji.
///
/// Supports both full country names (from Race.country) and nationality
/// adjectives (from the Ergast API Driver.nationality field).
String countryFlag(String countryOrNationality) {
  final key = countryOrNationality.trim().toLowerCase();
  return _flagMap[key] ?? _defaultFlag;
}

const String _defaultFlag = '\u{1F3C1}'; // chequered flag fallback

const Map<String, String> _flagMap = {
  // — F1 race countries —
  'bahrain': '🇧🇭',
  'saudi arabia': '🇸🇦',
  'australia': '🇦🇺',
  'japan': '🇯🇵',
  'china': '🇨🇳',
  'usa': '🇺🇸',
  'united states': '🇺🇸',
  'italy': '🇮🇹',
  'monaco': '🇲🇨',
  'spain': '🇪🇸',
  'canada': '🇨🇦',
  'austria': '🇦🇹',
  'uk': '🇬🇧',
  'united kingdom': '🇬🇧',
  'great britain': '🇬🇧',
  'hungary': '🇭🇺',
  'belgium': '🇧🇪',
  'netherlands': '🇳🇱',
  'the netherlands': '🇳🇱',
  'azerbaijan': '🇦🇿',
  'singapore': '🇸🇬',
  'mexico': '🇲🇽',
  'brazil': '🇧🇷',
  'qatar': '🇶🇦',
  'uae': '🇦🇪',
  'united arab emirates': '🇦🇪',
  'abu dhabi': '🇦🇪',
  'france': '🇫🇷',
  'germany': '🇩🇪',
  'portugal': '🇵🇹',
  'turkey': '🇹🇷',
  'russia': '🇷🇺',
  'south korea': '🇰🇷',
  'korea': '🇰🇷',
  'india': '🇮🇳',
  'malaysia': '🇲🇾',
  'south africa': '🇿🇦',
  'argentina': '🇦🇷',
  'switzerland': '🇨🇭',
  'sweden': '🇸🇪',
  'new zealand': '🇳🇿',
  'poland': '🇵🇱',
  'denmark': '🇩🇰',
  'finland': '🇫🇮',
  'colombia': '🇨🇴',
  'venezuela': '🇻🇪',
  'thailand': '🇹🇭',
  'indonesia': '🇮🇩',
  'ireland': '🇮🇪',
  'czech republic': '🇨🇿',

  // — Nationality adjectives (Ergast API) —
  'bahraini': '🇧🇭',
  'saudi': '🇸🇦',
  'australian': '🇦🇺',
  'japanese': '🇯🇵',
  'chinese': '🇨🇳',
  'american': '🇺🇸',
  'italian': '🇮🇹',
  'monegasque': '🇲🇨',
  'spanish': '🇪🇸',
  'canadian': '🇨🇦',
  'austrian': '🇦🇹',
  'british': '🇬🇧',
  'hungarian': '🇭🇺',
  'belgian': '🇧🇪',
  'dutch': '🇳🇱',
  'azerbaijani': '🇦🇿',
  'singaporean': '🇸🇬',
  'mexican': '🇲🇽',
  'brazilian': '🇧🇷',
  'qatari': '🇶🇦',
  'emirati': '🇦🇪',
  'french': '🇫🇷',
  'german': '🇩🇪',
  'portuguese': '🇵🇹',
  'turkish': '🇹🇷',
  'russian': '🇷🇺',
  'korean': '🇰🇷',
  'indian': '🇮🇳',
  'malaysian': '🇲🇾',
  'south african': '🇿🇦',
  'argentine': '🇦🇷',
  'swiss': '🇨🇭',
  'swedish': '🇸🇪',
  'new zealander': '🇳🇿',
  'polish': '🇵🇱',
  'danish': '🇩🇰',
  'finnish': '🇫🇮',
  'colombian': '🇨🇴',
  'venezuelan': '🇻🇪',
  'thai': '🇹🇭',
  'indonesian': '🇮🇩',
  'irish': '🇮🇪',
  'czech': '🇨🇿',
};
